name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build application with open-next
        run: npm run build

      - name: Copy .next directory to S3
        run: aws s3 cp build s3://cometolaser.com/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Invalidate CloudFront distribution cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_DEFAULT_CLOUDFRONT }} \
            --paths "/*"
